//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionReferee
    {
        public CompetitionReferee()
        {
            this.Name = "";
            this.IsMainReferee = false;
            this.Game = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int CompetitionId { get; set; }
        public bool IsMainReferee { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual ICollection<Game> Game { get; set; }
    }
}
