//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public Competition()
        {
            this.Name = "";
            this.Description = "";
            this.Stage = new HashSet<Stage>();
            this.Place = new HashSet<Place>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ManaSchedule.Models.GameType Type { get; set; }
    
        public virtual ICollection<Stage> Stage { get; set; }
        public virtual ICollection<Place> Place { get; set; }
    }
}
