//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionScore
    {
        public CompetitionScore()
        {
            this.Description = "";
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int TeamId { get; set; }
        public double Score { get; set; }
        public double Place { get; set; }
        public string Description { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Team Team { get; set; }
    }
}
