//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Name = "";
            this.Description = "";
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StageId { get; set; }
        public int PlaceId { get; set; }
        public int Team1Id { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Place Place { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
