//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResult
    {
        public GameResult()
        {
            this.Description = "";
            this.Values = new HashSet<GameResultValue>();
        }
    
        public int Id { get; set; }
        public int GameId { get; set; }
        public int CompetitionRefereeId { get; set; }
        public string Description { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual CompetitionReferee Referee { get; set; }
        public virtual ICollection<GameResultValue> Values { get; set; }
    }
}
