//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Name = "";
            this.Description = "";
            this.Team1Win = false;
            this.Team2Win = false;
            this.Team1Cancel = false;
            this.Team2Cancel = false;
            this.GameResults = new HashSet<GameResult>();
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int StageId { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> Team2_Id { get; set; }
        public Nullable<bool> Team1Missed { get; set; }
        public Nullable<bool> Team2Missed { get; set; }
        public bool Team1Win { get; set; }
        public bool Team2Win { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<System.DateTime> FromFact { get; set; }
        public Nullable<System.DateTime> ToFact { get; set; }
        public bool Team1Cancel { get; set; }
        public bool Team2Cancel { get; set; }
        public string PlaceName { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Place Place { get; set; }
        public virtual Team Team { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Team Team2 { get; set; }
        public virtual Game ParentGame1 { get; set; }
        public virtual Game ParentGame2 { get; set; }
        public virtual ICollection<GameResult> GameResults { get; set; }
    }
}
