//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaSchedule.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db : DbContext
    {
        public Db()
            : base("name=Db")
        {
        }
    
        public virtual DbSet<Team> TeamSet { get; set; }
        public virtual DbSet<Game> GameSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Stage> StageSet { get; set; }
        public virtual DbSet<Competition> CompetitionSet { get; set; }
        public virtual DbSet<Place> PlaceSet { get; set; }
        public virtual DbSet<TeamCompetition> TeamCompetitionSet { get; set; }
        public virtual DbSet<CompetitionReferee> CompetitionRefereeSet { get; set; }
        public virtual DbSet<GameResult> GameResultSet { get; set; }
        public virtual DbSet<GameResultValue> GameResultValueSet { get; set; }
        public virtual DbSet<CompetitionScore> CompetitionScoreSet { get; set; }
        public virtual DbSet<StageGen> StageGenSet { get; set; }
    }
}
